### ISSUE TITLE
Features request

### ISSUE THREAD

**Issue by duceppemo** [USDA-VS/snp_analysis#6]
Hi Tod,

I think that adding these 2 options would make the usage of the pipeline more flexible:
1. Add an option to run only the "all" tree from the VCF files. All cores would be used for the RAxML job.
2. Add an option to control the number of sample to parallel process. This would be useful if the number of samples to process in small. Say you have only 2 samples and one of them has super big fastq files compared to the other one, than you could assign to run only 1 sample in parallel. That would assign all the cores to 1 sample, run them in series and cut down the run time by much.

I would actually use those 2 options often. We rarely have lots of new strains to process here...
Thanks,
Marco

**Comment by stuber** [comment]
How would the "all" tree be different from the current -a option?  Would it be to just run the all tree minus the groups?

I'll add the processor control as a new option. 

Thanks,

**Comment by duceppemo** [comment]
I would just run the all tree, but no trees from the groups. So basically bypass the sorting of the vcf file. Just grab them all to throw them at RAxML using all the cores. It would require a new flag. The "-a" option is still useful (i.e. getting all the group trees + a tree of all vcf).

**Comment by stuber** [comment]
Added -p and -o options.  -p can take the number of processors to use.  -o will run only the all_vcf.  Let me know if you get a chance to try.

**Comment by duceppemo** [comment]
Ok, I tried running it on the 4459 vcf collection using the "-o" option and it crashed:

1. it was complaining about not all files being 'vcf' The problem was caused by a file name "remove.txt" that was created by the pipeline. So I guess that has to be fixed.

2. Once I removed the "remove.txt"  file, that checkpoint cleared, but it still crashed. It was complaining that a vcf file was missing. I didn't have much time to figure out why. I'll work on that tomorrow.

I didn't have a chance to try the "-p" option. What it does exactly? What I was hoping for was to be able to limit the number of parallel processing so more CPU are assigned per sample. Is that what "-p" does? The description let me think that it limits the number of CPUs rather than the number of samples to be parallel processed...

**Comment by stuber** [comment]
I'll take another look at the -o option.  I'm going to make a new branch and revert the master.  After more testing I'll merge branches.

Option -p will give a top cpu limit.  So if you have 48 cores and you give it 8 it will only use those 8.  Checking and allotting resources is done the some for step 1 and 2.  It is done immediately and carries through the rest of the script.  There is a "cpu_count", and "limited_cpu_count".   "limited_cpu_count" is used to allot the number of samples to run concurrently (step 1) as a pooled process.  It also limits the "max_workers".  Without this limit things are unstable.  Since working with both python's concurrency and the system calls (bwa, FreeBayes, RAxML) which also have their own parallel calls, after a lot of testing, the current setup has shown to provide the right balance of speed and stability.  The limiting factor for processing large files will be system calls.  Their settings are hard coded and already set high.  Setting higher will likely not give much speed improvement.  My thought with the -p option is smaller files could be batched and ran with a low -p value, say 8 and then a larger file or files could be started with default parameters.  If input files were batched right I think one could get more processing out of a system within a set amount of time.

**Comment by stuber** [comment]
-o option fixed (hopefully :) and updated

**Comment by duceppemo** [comment]
-o option is working now. I have a code modificaiton suggestion to use all cores with RAxML when using it. At line 1519, where you set the CPU count for RAxML we can read:

```
if arg_options['cpu_count'] < 20:
        raxml_cpu = 2
else:
    raxml_cpu = int(arg_options['cpu_count'] / 10)
```
If you change that code for the following, you will achieve that:
```
if arg_options['only_all_vcf']:  # use all CPUs for raxml since only one insatnce needs to run
    raxml_cpu = arg_options['cpu_count']
else:
    if arg_options['cpu_count'] < 20:
        raxml_cpu = 2
    else:
        raxml_cpu = int(arg_options['cpu_count'] / 10)
```

**Comment by stuber** [comment]
Added feature, but haven't been able to test speed improvements.
